In [6]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt
A = [[1, 2, 3], [4, 0, 6], [7, 8, 9]]
B = [12, 2, 1]
A0 = np.linalg.solve(A, B)
print('Решение с помощью функции solve:')
print(A0)
print('')
A1 = np.linalg.inv(A)
print('Решение через обратную матрицу:')
print(A1)
#print("det =", np.linalg.det(A))
A2 = np.dot(A1, B)
print('')
print(A2)
print('')
print('Оба решения совпадают!')

Решение с помощью функции solve:
[-9.2         0.9         6.46666667]

Решение через обратную матрицу:
[[-0.8         0.1         0.2       ]
 [ 0.1        -0.2         0.1       ]
 [ 0.53333333  0.1        -0.13333333]]

[-9.2         0.9         6.46666667]

Оба решения совпадают!
