In [14]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np
import scipy 
import scipy.linalg

A = np.array([[ 1,  2,  3],
              [ 2, 16, 21],
              [ 4, 28, 73]])
B = np.array([10, 53, 171])
A1 = np.array([[ 1,  2,  3,  10],
               [ 2, 16, 21,  53],
               [ 4, 28, 73, 171]])
D = np.linalg.det(A)
P, L, U = scipy.linalg.lu(A)
r_A = np.linalg.matrix_rank(A, 0.0001)
r_A1 = np.linalg.matrix_rank(A, 0.0001)

print('LU-разложение исходной матрицы А:')
print()
print(P)
print()
print(L)
print()
print(U)
print()
print(f'Детерминант исходной матрицы А: {D}')
print()
print(f'Придуманный вектор правых частей: {B}')
print()
print(f'Ранг матрицы A:  {r_A}')
print(f'Ранг матрицы A1: {r_A1}')
print('Ранги исходной и расширенной матрицы равны, ранг равен количеству неизвестных,')
print('детерминант не равен нулю - система имеет единственное решение')
print()
print('Решение полученной линейной системы трёх уравнений:')
print(np.linalg.solve(A, B))

LU-разложение исходной матрицы А:

[[0. 1. 0.]
 [0. 0. 1.]
 [1. 0. 0.]]

[[ 1.    0.    0.  ]
 [ 0.25  1.    0.  ]
 [ 0.5  -0.4   1.  ]]

[[  4.    28.    73.  ]
 [  0.    -5.   -15.25]
 [  0.     0.   -21.6 ]]

Детерминант исходной матрицы А: 432.00000000000017

Придуманный вектор правых частей: [ 10  53 171]

Ранг матрицы A:  3
Ранг матрицы A1: 3
Ранги исходной и расширенной матрицы равны, ранг равен количеству неизвестных,
детерминант не равен нулю - система имеет единственное решение

Решение полученной линейной системы трёх уравнений:
[3.44444444 0.11111111 2.11111111]
