In [2]:
%matplotlib inline
import numpy as np
import matplotlib.pyplot as plt

A = [[1, 2, -1], [3, -4, 0], [8, -5, 2], [2, 0, -5], [11, 4, -7]]
B = [1, 7, 12, 7, 15]
print('Поиск псевдорешения методом наименьших квадратов:')
np.linalg.lstsq(A, B)

Поиск псевдорешения методом наименьших квадратов:


(array([ 1.13919353, -0.90498444, -0.9009803 ]),
 array([0.71523211]),
 3,
 array([15.2817306 ,  9.59852942,  3.65197794]))