In [4]:
%matplotlib inline
import matplotlib.pyplot as plt
import numpy as np

A = np.array([ [1, 2, 3], [4, 5, 6], [7, 8, 9] ])
B = np.array([2, 5, 11])
Q, R = np.linalg.qr(A)

print('Исходная матрица A:')
print(A)
print()
print('Матрица Q:')
print(Q)
print()
print('Матрица R:')
print(R)
print()
print('Проверка корректности QR-разложения. При умножении Q на R получаем исходную матрицу A:')
print(np.dot(Q, R))
print()
print('Проверка ортогональности матрицы Q: произведение Q и транспонированной Q дает единичную матрицу:')
print(np.dot(np.transpose(Q), Q))
print()
print('Подматрица R1 размером 2х2:')
R1 = R[:2, :2]
print(R1)
print()
print('Подматрица B1, соответствует системе, определяющей X1:')
B1 = np.dot(np.transpose(Q), B)[:2]
print(B1)
print()
X1 = np.linalg.solve(R1, B1)
print('Решение этой линейной системы X1:')
print(X1)
print()
X = np.append(X1, 0)
print('К решению X1 добавляем нулевой компонент вектора X2.')
print('Получено псевдорешение для исходной линейной системы:')
print(X)
print()
print('Норма вектора X:')
print(np.linalg.norm(X))
print()
print('Норма вектора невязки исходной линейной системы:')
print(np.linalg.norm(np.dot(A, X) - B))


Исходная матрица A:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Матрица Q:
[[-0.12309149  0.90453403  0.40824829]
 [-0.49236596  0.30151134 -0.81649658]
 [-0.86164044 -0.30151134  0.40824829]]

Матрица R:
[[-8.12403840e+00 -9.60113630e+00 -1.10782342e+01]
 [ 0.00000000e+00  9.04534034e-01  1.80906807e+00]
 [ 0.00000000e+00  0.00000000e+00 -8.88178420e-16]]

Проверка корректности QR-разложения. При умножении Q на R получаем исходную матрицу A:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Проверка ортогональности матрицы Q: произведение Q и транспонированной Q дает единичную матрицу:
[[ 1.00000000e+00 -2.48218629e-16 -2.62094065e-17]
 [-2.48218629e-16  1.00000000e+00  2.82872043e-17]
 [-2.62094065e-17  2.82872043e-17  1.00000000e+00]]

Подматрица R1 размером 2х2:
[[-8.1240384  -9.6011363 ]
 [ 0.          0.90453403]]

Подматрица B1, соответствует системе, определяющей X1:
[-1.21860576e+01  3.55271368e-15]

Решение этой линейной системы X1:
[1.50000000e+00 3.92767275e-15]

К решению X1 добавляем нулевой компон